server:
  port: 8080

spring:
  rabbitmq:
    host: 192.168.88.128
    username: root
    password: 123456
    port: 5672
    #开启回调确认
    # CORRELATED:发布消息成功到交换器后会触发回调方法
    # NONE:禁用发布确认模式，是默认值
    # SIMPLE:Use {@code RabbitTemplate#waitForConfirms()} (or {@code waitForConfirmsOrDie()} within scoped operations
    publisher-confirm-type: correlated
    # 交换机消息路由不到队列 回退
    publisher-returns: true